### PR TITLE
Set produce_fc2's base _displacement_dataset to be _phonon_displaceme…

### PR DESCRIPTION
**Pull request by tpurcell90**
Changes the default displacement dataset in produce_fc2 to _phonon_displacement_dataset. This would allow a user to pull the _displacement_dataset and _phonon_displacement_dataset to get the force sets used to calculate the second and third order force constants.

### CODE REVIEW

**Comment by atztogo** [comment]
Does this work when --dim-fc2 is not set?

**Comment by tpurcell90** [comment]
The examples work without --dim-fc2 set (I get the the same results for the Si examples if I add disp_fc2.yaml and FORCES_FC2 files from the third order files).

I typically use the python api, and with that if the phonon_supercell_matrix is not set then it will throw an error. However this can be fixed by checking if _phonon_displacement_dataset is None and if not using the _displacement_dataset.

**Comment by atztogo** [comment]
I understand. I didn't merge your pull request but I made a commit on develop branch directory. See fc985129e82f590da1daf7232738ca094afee674. Can you test it?

**Comment by tpurcell90** [comment]
The second else was deleted so if you add it back in (see below) then it works. 

```
        if displacement_dataset is None:
            if self._phonon_displacement_dataset is None:
                disp_dataset = self._displacement_dataset
            else:
                disp_dataset = self._phonon_displacement_dataset
        else:
            disp_dataset = displacement_dataset

```

**Comment by atztogo** [comment]
I think the code on develop branch is as you write. https://github.com/atztogo/phono3py/blob/fc985129e82f590da1daf7232738ca094afee674/phono3py/phonon3/__init__.py#L257
Do I understand your comment?

**Comment by tpurcell90** [comment]
So it is, I must have accidentally deleted the line without realizing it. The code works for me.

**Comment by atztogo** [comment]
Can I close this pull request?

**Comment by atztogo** [comment]
I close this issue.

**Pull request closed without merging**
